{{- if and (eq .Values.mode "serve") .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sheaft.fullname" . }}
  labels:
    {{- include "sheaft.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "sheaft.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
{{- end }}
