version: 2

project_name: sheaft
dist: dist

builds:
  - id: sheaft
    main: ./cmd/sheaft
    binary: sheaft
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w

archives:
  - id: binaries
    ids:
      - sheaft
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

sboms:
  - id: archives
    artifacts: archive

snapshot:
  version_template: "{{ if .Env.APP_VERSION }}{{ .Env.APP_VERSION }}{{ else }}0.0.0-dev{{ end }}"

source:
  enabled: true
  name_template: "{{ .ProjectName }}_{{ .Version }}_source"

changelog:
  disable: true
