schema_version: "1.0"

predicates:
  catalog.checkout.success:
    type: all_of
    services:
      - checkout
      - inventory
  frontend:GET /checkout:
    type: all_of
    services:
      - frontend
      - checkout
      - inventory
  frontend:GET /health:
    type: all_of
    services:
      - frontend

endpoint_weights:
  checkout:POST /process: 0.6
  frontend:GET /checkout: 0.4
